before:
  hooks:
  - go mod tidy

env:
  - IMAGE_TAG={{.Tag}}
  
project_name: cmsnrctl

builds:
  - ldflags: "-extldflags= -w -X 'github.com/gamer22026/cmsnr/cmd.Version={{.Tag}}'"
    env:
      - "CGO_ENABLED=0"
      - "GO111MODULE=on"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
source:
  enabled: true
